### ISSUE TITLE
[Binance] Error when parsing currency pairs

### ISSUE THREAD

**Issue by janakerman** [bitrich-info/xchange-stream#100]
When deserialising tickers (in `ProductBinanceWebSocketTransaction`) we split the `symbol` from characters 0-3 and 4-6 to get the two currencies in the pair. 

Binance returns a currency AE, and when it is the base this logic causes a StringOutOfBoundsException as we assume a pair always consists of six characters.

e.g `AEBTC`, `AEETH`, `AEBNB`

Infact, looking at the response from `.getSymbols()`, there's actually a bunch of symbols that could cause problems.

**Comment by trojanflash** [comment]
my quick fix
[xchange-binance.zip](https://github.com/bitrich-info/xchange-stream/files/1743103/xchange-binance.zip)

**Comment by aleks-azen** [comment]
I've got a pull request that fixes this issue waiting to be merged into the current develop branch of the xchange project, once that moves to release and this project updates dependencies it'll be fixed

**Comment by Flemingjp** [comment]
New release should have fixed this, if @aleks-azen suggestion was correct.

**Comment by badgerwithagun** [comment]
Yes, it certainly has no issues with CLOAK for example, or NANO.

**Comment by badgerwithagun** [comment]
Feel free to close this, @Flemingjp
