### ISSUE TITLE
Low performance on Observables

### ISSUE THREAD

**Issue by nodarret** [bitrich-info/xchange-stream#101]
All Observables are handled on netty thread. 
For GDAX when all tickers are on one websocket channel it gives very poor performance and huge delays.

I tried use subscribeOn(Schedulers.computation()) on my code but it wont work somehow.
Adding for every exchange at the beginning of getOrderBook method observeOn(Schedulers.computation()) helps - every ticker is handled by spearate thread from computation pool.

Do you have similar observations on performance?

**Comment by dozd** [comment]
Using `observeOn` on the "client side" is good solution. But I don't understand fully of the problem if this is the good case for it. If you can prepare scenario into `GDAXManualTest` where you encountering this problem I can look into it more deeply.

**Comment by nodarret** [comment]
I was monitoring performance on GDAX and found that rebuilding order book every tick is very expensive. Also using observeOn with scheduler can result with java heap space, so it should be used with back pressure. It is hard for me to change every exchange library to get better performance so i decided to write my own simple solution that suits my needs.
Thanks for your interest!
