### ISSUE TITLE
Can we please have an updated version of Xchange

### ISSUE THREAD

**Issue by omeed12** [bitrich-info/xchange-stream#106]
Seems like the latest version of Xchange is 4.3.3, which has GDAX sandbox support. Can we please update Xchange-stream to use this version? 

Thank you very much!

**Comment by traviscollins** [comment]
You can force your maven based project to use any xchange version you want (as long as you don't attempt to call any new functions in the interfaces). 


    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.knowm.xchange</groupId>
                <artifactId>xchange-gdax</artifactId>
                <version>${xchange.version}</version>
            </dependency>
            <dependency>
                <groupId>org.knowm.xchange</groupId>
                <artifactId>xchange-core</artifactId>
                <version>${xchange.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

**Comment by dozd** [comment]
Newest Xchange is already in the develop branch and will be released with new version
