### ISSUE TITLE
BitFinex Streaming Orderbook is broken

### ISSUE THREAD

**Issue by traviscollins** [bitrich-info/xchange-stream#111]
The implementation for BitFinex streaming order book is completely broken. It's subscribing to the "R0" precision - which is on a per order entry change basis. But it's then treating those as aggregate levels (instead of individual entries and performing aggregation). The result is that the order books on presented on the observable have negative values for "amount". 

I'll work on a fix for this.

**Comment by dozd** [comment]
Thanks for the fix!
