### ISSUE TITLE
Unable to parse ticker transaction

### ISSUE THREAD

**Issue by woxip0** [bitrich-info/xchange-stream#135]
Hi, I am using Xchange 4.3.4 and Xchange-stream 4.3.1 and getting this error:
```
OnErrorNotImplementedException: Unable to parse ticker transaction
```
It comes to a missing parameter for the constructor of BinanceTicker24h: (String symbol) on TickerBinanceWebsocketTransaction.

Do you have any plans for migrating your xchange dependency to 4.3.4 soon?

**Comment by mahieddine** [comment]
see #140
