### ISSUE TITLE
Dispose method removes channel synchronously but messages are keep recieving - NullPointerException is raised!

### ISSUE THREAD

**Issue by pchertalev** [bitrich-info/xchange-stream#144]
public abstract class NettyStreamingService<T> {

protected void handleChannelMessage(String channel, T message) {

         /////// NPE raised here if dispose method called but messages has been recieved 
        ObservableEmitter<T> emitter = channels.get(channel).emitter;   
         /////// because channels.get(channel) returns null after dispose calling

        if (emitter == null) {
            LOG.debug("No subscriber for channel {}.", channel);
            return;
        }

        emitter.onNext(message);
    }

I belive we need to check channels.get(channel) as well and type "No subscriber for channel" in case it is null instead of NPE

**Comment by etricky** [comment]
I'm hitting this issue as well. Every time I end a subscription by calling the dispose method I immediately get a NPE as channels.get(channel) is still being invoked!

**Comment by pchertalev** [comment]
solved by #191
