### ISSUE TITLE
Module names don't mix very well with xchange lib

### ISSUE THREAD

**Issue by daybyter** [bitrich-info/xchange-stream#149]
Since you can't trade with the xchange-stream lib alone, you also have to include xchange (or a similar lib) in a trading app. But the modules there have the same name (xchange-poloniex-<version>.jar  as an example) as the xchange-stream jars. That works at the moment, because the versions differ, but if xchange and xchange-stream have a release with the same version nr, it will cause problems.
Maybe name the xchange-stream modules xchange-stream-poloniex-<version>.jar , or so.

**Comment by dozd** [comment]
Duplicate #84
