### ISSUE TITLE
Hitbtc subscription fails for currency pairs where id does not equal base + counter

### ISSUE THREAD

**Issue by davidjirovec** [bitrich-info/xchange-stream#167]
For example
```
{
        "id": "XRPUSDT",
        "baseCurrency": "XRP",
        "quoteCurrency": "USD",
        "quantityIncrement": "1",
        "tickSize": "0.0001",
        "takeLiquidityRate": "0.001",
        "provideLiquidityRate": "-0.0001",
        "feeCurrency": "USD"
}
```
To me it seems unpredictable if id will contain USD or USDT. Exchange instance would probably have to internally store id expected by Hitbtc.

**Comment by pchertalev** [comment]
Sorry, I don't clear problem.
XChange Currency pairs contains correct values for instruments:
`       XRP_USD = new CurrencyPair(Currency.XRP, Currency.USD);
        XRP_USDT = new CurrencyPair(Currency.XRP, Currency.USDT);
`
There is no problem to subscribe on CurrencyPair.XRP_USD instrument - it works correctly:

`        Disposable orderBookObserver = exchange.getStreamingMarketDataService().getOrderBook(CurrencyPair.XRP_USDT).subscribe(orderBook -> {
            LOG.info("First ask: {}", orderBook.getAsks().get(0));
            LOG.info("First bid: {}", orderBook.getBids().get(0));
        }, throwable -> LOG.error("ERROR in getting order book: ", throwable));
`
I see problem only when I try to subscribe on instrument which is missing on HITBTC like CurrencyPair.XRP_USD - HITBTC responds error:
`
{
  "jsonrpc": "2.0",
  "error": {
    "code": 2001,
    "message": "Symbol not found",
    "description": "Try get /api/2/public/symbol, to get list of all available symbols."
  },
  "id": 1416525893
}
`
I see infinite resubscribing without any error in log. I going to fix it.

**Comment by davidjirovec** [comment]
```
public class HitbtcManualExample {

    public static void main(String[] args) {
        final ExchangeSpecification exchangeSpecification = new ExchangeSpecification(HitbtcStreamingExchange.class);
        exchangeSpecification.setShouldLoadRemoteMetaData(true);
        StreamingExchange exchange = StreamingExchangeFactory.INSTANCE.createExchange(exchangeSpecification);

        exchange.connect().blockingAwait();

        for (final CurrencyPair currencyPair : exchange.getExchangeSymbols()) {
            exchange.getStreamingMarketDataService().getOrderBook(currencyPair).subscribe();
        }

        try {
            Thread.sleep(10000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
    }
}
```
results in
```
21:47:58.611 [main] DEBUG info.bitrich.xchangestream.hitbtc.HitbtcStreamingService - Sending message: {"id":1250507845,"method":"subscribeOrderbook","params":{"symbol":"EBTCBTC"}}
...
21:47:59.780 [nioEventLoopGroup-2-1] DEBUG info.bitrich.xchangestream.service.netty.JsonNettyStreamingService - Received message: {"jsonrpc":"2.0","error":{"code":2001,"message":"Symbol not found","description":"Try get /api/2/public/symbol, to get list of all available symbols."},"id":1250507845}
```
it is probably the issue you described - because the currency pair id expected by exchange is not the one generated by xchange-stream

**Comment by pchertalev** [comment]
I created pool request with error handling fix for HitBTC subscription:
https://github.com/bitrich-info/xchange-stream/pull/169

**Comment by dozd** [comment]
Merged
