### ISSUE TITLE
Exception while subscribing to Bitstemp OrderBook

### ISSUE THREAD

**Issue by hterhors** [bitrich-info/xchange-stream#18]
Hi there,

i am currently testing your example code. In particular i am interested in the orderbook subscription. if i try your code example I get the following exception:

com.fasterxml.jackson.databind.JsonMappingException: Can not construct instance of org.knowm.xchange.bitstamp.dto.marketdata.BitstampOrderBook, problem: null

Although, the detailed error messages shows bids and asks I get this error.

As far as I know, Bistamp does not support timestamps in placed trades in the Orderbook. I though all timestamps of the orders in the OrderBook are null. Maybe that cause the problem?

Kind regards,
Hendrik

**Comment by timmolter** [comment]
Are you trying out the source code on the develop or master branch? What class are you running?

**Comment by hterhors** [comment]
Hi,

I tried that code on your start page.

https://github.com/bitrich-info/xchange-stream

For that I included the 2 maven dependencies with the newest version 4.2.2.
(I am not sure what branch they are of)
And then I copied the source code from your Example into my project.
That's basically it.

The streaming for Trades works perfectly fine.

Thanks,
Hendrik

**Comment by dozd** [comment]
I think there were some change in bitstamp api. I'll investigate.

**Comment by dozd** [comment]
I cannot reproduce on develop branch.

**Comment by dozd** [comment]
Try latest version xchange-stream:2.3.2

**Comment by hterhors** [comment]
I thought latest version is 4.2.2 ? My Maven looks like this:

```
		<dependency>
			<groupId>info.bitrich.xchange-stream</groupId>
			<artifactId>xchange-stream-core</artifactId>
			<version>4.2.2</version>
		</dependency>

		<dependency>
			<groupId>info.bitrich.xchange-stream</groupId>
			<artifactId>xchange-bitstamp</artifactId>
			<version>4.2.2</version>
		</dependency>
```

I still get the error :/

Thanks, Hendrik

**Comment by dozd** [comment]
Sorry, I ment version 4.2.3. That should work.

**Comment by hterhors** [comment]
Thank you very much! Now it works.
