### ISSUE TITLE
Implement Bitmex exchange with bounty

### ISSUE THREAD

**Issue by makarid** [bitrich-info/xchange-stream#19]
Hello,i am offering a bounty of 50mBTC in order someone to implement the Bitmex exchange,using websocket connection.I am mostly interested for XBTUSD contracts.I am waiting for your response,please ask me if you want to specify anything.Thanks a lot!

**Comment by cymp** [comment]
You will have no support here for websocket, only REST api calls.

**Comment by makarid** [comment]
There are not so many developers here?

**Comment by timmolter** [comment]
@cymp He did open this issue on `bitrich-info/xchange-stream`. Did you miss that?

**Comment by cymp** [comment]
Oops, my bad, need to get some sleep someday.

**Comment by dozd** [comment]
Why is this one closed? :-) It's in xchange-stream, isn't?
