### ISSUE TITLE
GDAX support?

### ISSUE THREAD

**Issue by pirocks** [bitrich-info/xchange-stream#2]
Any plans to support https://www.gdax.com/? it has a fix and rest websocket, documented here:https://docs.gdax.com/#websocket-feed and here: https://docs.gdax.com/#fix-api.

**Comment by dozd** [comment]
Imeplemented in #3 #4. Released in version 4.2.1. Will be on maven in few hours

**Comment by lucarosellini** [comment]
@pirocks, let me know if you find any problem with this code
