### ISSUE TITLE
[Binance] Order book gets out of sync after a while

### ISSUE THREAD

**Issue by badgerwithagun** [bitrich-info/xchange-stream#203]
I've noticed that an order book snapshot gets out of sync over time (even including #197).  We're definitely not using _quite_ the same approach described in Binance's docs for accurately syncing via the streaming API.  The solution is probably to follow that more slavishly and/or to do periodic refreshes from the pull API.

I'll be looking into this properly when I get a chance. Just recording it here for reference.

**Comment by davidjirovec** [comment]
How do you check if it gets out of sync? In which way are they out of sync? Missing values? Wrong values?

There is also repo with implementation of Java client for their api https://github.com/binance-exchange/binance-java-api

**Comment by davidjirovec** [comment]
I would guess it might be an issue of xchange-stream not working with `lastUpdateId`

**Comment by badgerwithagun** [comment]
Duplicate of #86
