### ISSUE TITLE
Futures API of OkEx not supported.

### ISSUE THREAD

**Issue by stgrandet** [bitrich-info/xchange-stream#204]
API specification: https://github.com/okcoin-okex/API-docs-OKEx.com/blob/master/API-For-Futures-EN/WebSocket%20API%20for%20FUTURES.md

**Comment by stgrandet** [comment]
Seems already supported in version 4.3.3.

**Comment by Flemingjp** [comment]
@stgrandet I'm assuming this issue is therefore resolved. Open a new issue if this is not the case
