### ISSUE TITLE
[HitBTC] Is there a way for me to know whether my trades get executed ?

### ISSUE THREAD

**Issue by szd116** [bitrich-info/xchange-stream#229]
Is there a way for me to know whether my trades get executed ? for instance, I would like to know the status of my trades, whether it's partial fill, or full fill through web socket ? At this point I can see trades through web sockets for instance:
TRADE: {} Trade [type=BID, originalAmount=0.02, currencyPair=BTC/USD, price=6657.81, timestamp=Tue Oct 09 04:56:05 EDT 2018, id=377800796]

There is no status of these trades. The instance I am interested in particular is HITBTC. Thanks.

**Comment by fynnfluegge** [comment]
I would recommend to check your own trade status via rest API and your account infos

**Comment by szd116** [comment]
Making a API call not only it's slow but there is a rate limit to it.

**Comment by Flemingjp** [comment]
Looking at the documentation for HitBTC there is some endpoints that [maybe useful ](https://api.hitbtc.com/#socket-trading). However it appears it is not yet implemented in this library.

**Comment by badgerwithagun** [comment]
Execution report support is only just starting to arrive. Status:

- We have support for GDAX (added in #160).
- Support for Bitfinex is underway on #209.
- I am working on support for Binance (PR soon).

HitBTC support is currently not available.  @szd116, feel free to raise a feature request.  There might be other HitBTC users who would be keen to implement it.  In the meantime you may be interested to know that you can get the published rate limits  from `Exchange.getExchangeMetaData()` (see https://knowm.org/javadocs/xchange/org/knowm/xchange/dto/meta/ExchangeMetaData.html).  I personally write my polling code to fit within these limits when I am using exchanges with no support for this stuff.

**Comment by szd116** [comment]
Thank you gentlemen for the prompt reply. I will raise a request.

**Comment by Flemingjp** [comment]
#232
