### ISSUE TITLE
[OKEX] needs to handle GZIP compressed message

### ISSUE THREAD

**Issue by declan94** [bitrich-info/xchange-stream#238]
According to the latest API document of OKEX:
https://github.com/okcoin-okex/API-docs-OKEx.com/blob/b0617f4e88a316b74661c24da99cb06d95d62086/README-en.md

"All the messages returning from WebSocket API will be optimized by GZIP compression. All users will be required to decompress the messages by themselves with the methods they find most appropriate. Method of getting compressed messages: add parameter "compress=true" to request URL. Our system will eventually ignore the "compress" parameter and return the compressed message directly.
Compressed message: wss://real.okex.com:10441/websocket?compress=true;
Uncompressed message: wss://real.okex.com:10441/websocket;"

Uncompressed interfaces will no longer be supported after October 24th, and they will always return the compressed messages then.

**Comment by badgerwithagun** [comment]
Related to #233?  That seeks to introduce compression support for Bitmex, although I've not looked into it in enough detail to tell if they are similar.

**Comment by declan94** [comment]
I think it could be solved through the same path of #233, which override the “getWebSocketClientExtensionHandler” method. But I haven’t found out how to implement a WebSocketClientExtensionHandler handling GZIP compressed messages.

**Comment by declan94** [comment]
Solved In #239
