### ISSUE TITLE
xchange-cexio NotYetImplementedForExchangeException

### ISSUE THREAD

**Issue by firepol** [bitrich-info/xchange-stream#247]
Hi, I was trying the cex.io websocket (OrderBooks) but I got `NotYetImplementedForExchangeException`

I see in fact in the `CexioStreamingMarketDataService` class that every method throws that exception.

I was wondering if the creator of that draft is planning to finalize it?

Thanks for letting me know & best regards

**Comment by fynnfluegge** [comment]
I'm going to add Cexio Support to my app, so will to implement it soon :)

**Comment by fynnfluegge** [comment]
What do you mean by false positive error in that context?

**Comment by firepol** [comment]
> What do you mean by false positive error in that context?

I mean I was getting an error and I was handling all errors in the same way: unsubscribe from the channel. Like that I basically lost all binance connections. After debugging it for a while I discovered that ignoring the error was the way to make it work. The funny thing was that I had no errors with binance together with many other exchanges: bitfinex, bitstamp, coinbase pro etc. the errors happened only when adding cexio to the mix.

So this maybe is a strange bug in the tooling I was using, which you can check out here, in case you are interested: https://github.com/firepol/ccxt-websockets-db-updater which is based on a fork of CCXT work in progress. But it works like a charm.

I created an issue for this weird problem: https://github.com/firepol/ccxt-websockets-db-updater/issues/4

Again, maybe in xchage-stream you won't have any trouble, sharing just in case...

**Comment by badgerwithagun** [comment]
Closing as stale. Please re-open if this is still an issue.
