### ISSUE TITLE
Bitmex streaming

### ISSUE THREAD

**Issue by lukaszaoralek** [bitrich-info/xchange-stream#25]
Please consider the PR #24 (and #22 )

**Comment by dozd** [comment]
Merged. Thanks. Let me know whether i should release new version to Central or you have another PR to be merged.

**Comment by dozd** [comment]
I updated the README, just check if I'm correct there.

**Comment by lukaszaoralek** [comment]
I think it's correct. I made PR #26  for poloniex, because old one is broke I guess, and this new one is based on wss://api2.poloniex.com (same api as websocket on their webpage)
