### ISSUE TITLE
BitfinexStreamingService Error with message should include symbol

### ISSUE THREAD

**Issue by firepol** [bitrich-info/xchange-stream#254]
Hi,

I was trying to subscribe to several order books for several of my favorite pairs, e.g. one pair "LSK/BTC" is invalid for bitfinex, which is fine. Just the error didn't really help me:

`[nioEventLoopGroup-2-1] ERROR info.bitrich.xchangestream.bitfinex.BitfinexStreamingService - Error with message: "symbol: invalid"`

Expected result:

The error message should include also the symbol, as follows:

`[nioEventLoopGroup-2-1] ERROR info.bitrich.xchangestream.bitfinex.BitfinexStreamingService - Error with message: "LSKBTC symbol: invalid"`

I debugged and seen that the error object looks as follows:

`{"channel":"book","pair":"SKBTC","prec":"P0","len":"100","event":"error","symbol":"LSKBTC","msg":"symbol: invalid","code":10300}`

In the `BitfinexStreamingService` I found where the error is logged:

`LOG.error("Error with message: " + message.get("msg"));`

It could be changed like this:

`LOG.error("Error with message: " + message.get("symbol") + " " + message.get("msg"));`

I'd like to submit a PR for this, would it be ok?

**Comment by badgerwithagun** [comment]
Yes please. Sounds quick enough, as long as message.get() doesn't throw an exception if the key isn't present (just returns null or something).
