### ISSUE TITLE
Bounties?

### ISSUE THREAD

**Issue by badgerwithagun** [bitrich-info/xchange-stream#258]
We've got a lot of feature requests but no-one motivated to implement them.  Unless you will actually use a feature there's no reason to implement one.  Crypto is a pretty mercenary game.

We could set up a bounty system (there are some good platforms out there) as XChange does, then there might be more people willing to implement new features, exchanges etc.

Worth a go?

**Comment by Flemingjp** [comment]
I was thinking of this too a while a go. I personally have been motivated and paid from bounties on XChange and have seen quick turn around on issues. Especially for implementing new exchanges

**Comment by jkolobok** [comment]
I think everything depends on bounty size. What features do you need and what's your budget?

**Comment by badgerwithagun** [comment]
I dont need anything (at least, nothing I can't code myself).

I am thinking about how XChange already encourages bounties for new features and how we can do the same thing.
