### ISSUE TITLE
Trade API test status

### ISSUE THREAD

**Issue by galic1987** [bitrich-info/xchange-stream#259]
I tested the 4.3.11 trades API with BTC_USD(T) and I can confirm the following working:
- BitFinex
- BitStamp
- HITBtc
- Poloniex2
- Gemini 
- OkCoin

Rest: 
Binance: Exception in thread "main" java.lang.IllegalArgumentException: Subscriptions must be made at connection time 
Can we merge this? https://github.com/bitrich-info/xchange-stream/issues/140

BitMex: INFO: Disconnected from the Exchange (after 10 seconds)

Poloniex : Just hangs in there 

CexIO:  Feature not yet implemented for exchange.

GDax: The ProductSubscription must be defined!

Bitflyer: INFO: Disconnected from the Exchange  (after 10 seconds)
 
Wex: we can remove this one 

Questions:
1) Did anyone tried contacting the exchanges to see if they would like provide developers for the project? It is in their interest. 
2) Can we create some simple unit tests?

**Comment by galic1987** [comment]
So I have created a BEAM pipeline example using this library 
Article: https://medium.com/@igalic/bigtable-beam-dataflow-cryptocurrencies-gcp-terraform-java-maven-4e7873811e86
Github: https://github.com/GoogleCloudPlatform/professional-services/tree/master/examples/cryptorealtime

Please include it in the examples section

Thx

**Comment by galic1987** [comment]
@badgerwithagun

**Comment by badgerwithagun** [comment]
@galic1987 - do you mean add it to [this section of the README](https://github.com/bitrich-info/xchange-stream#open-source-projects-using-xchange-stream)?

If so, just submit a pull request.

**Comment by galic1987** [comment]
https://github.com/bitrich-info/xchange-stream/pull/288
pls approve
