### ISSUE TITLE
Add SO_KEEPALIVE for websocket pipeline

### ISSUE THREAD

**Issue by alevohin** [bitrich-info/xchange-stream#262]
Now in `NettyStreamingService` websocket pipeline is created like
```
                b.group(eventLoopGroup)
                        .option(ChannelOption.CONNECT_TIMEOUT_MILLIS, java.lang.Math.toIntExact(connectionTimeout.toMillis()))
                        .channel(NioSocketChannel.class)
```
There is not optional `SO_KEEPALIVE` option, TCP keep alive is disabled and there is no way to enable it. Lets switch on `SO_KEEPALIVE` by default, because is some case there TCP keep alive is the only way to determinate broken TCP session.

**Comment by badgerwithagun** [comment]
We [already respond to websocket pings](https://github.com/bitrich-info/xchange-stream/blob/develop/service-netty/src/main/java/info/bitrich/xchangestream/service/netty/WebSocketClientHandler.java#L81) but agreed, this does seem to add some extra resilience.

Feel free to try it out and submit a pull request!

**Comment by alevohin** [comment]
I'll do PR a little bit later. Probably it would be great also to have not only responding on `PingWebSocketFrame` but also sending `PingWebSocketFrame` by itself.

**Comment by alevohin** [comment]
PR https://github.com/bitrich-info/xchange-stream/pull/263

**Comment by alevohin** [comment]
@Flemingjp yes, thank you! I'm closing it.
