### ISSUE TITLE
Minor synchronization issues with ConcurrentHashMap

### ISSUE THREAD

**Issue by berserkk** [bitrich-info/xchange-stream#276]
`ConcurrentHashMap` isn't fully correctly used in the code.
Yeah, you will not get `ConcurrentModificationException`, but there's possibility to get other issues like lost updates or `NullPointerException`. Of course, possibility is very low, but non-zero.

Here's examples:

https://github.com/bitrich-info/xchange-stream/blob/3819363226d16b193fe8c91ced11f958921ec1f7/service-netty/src/main/java/info/bitrich/xchangestream/service/netty/NettyStreamingService.java#L309-L311

`containsKey` and `put` are 2 different atomic operations. But the whole operation should be executed atomically. You can use [putIfAbsent](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ConcurrentHashMap.html#putIfAbsent-K-V-) or [computeIfAbsent](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ConcurrentHashMap.html#computeIfAbsent-K-java.util.function.Function-) methods to fix it.

https://github.com/bitrich-info/xchange-stream/blob/3819363226d16b193fe8c91ced11f958921ec1f7/service-netty/src/main/java/info/bitrich/xchangestream/service/netty/NettyStreamingService.java#L319-L322

Can be replaced with something like:

```
if (channels.remove(channelId) != null) {
    sendMessage(getUnsubscribeMessage(channelId)); 
}
```

but `getUnsubscribeMessage` must not use `channels` for fetching value by removed `channelId`.

https://github.com/bitrich-info/xchange-stream/blob/3819363226d16b193fe8c91ced11f958921ec1f7/service-netty/src/main/java/info/bitrich/xchangestream/service/netty/NettyStreamingService.java#L327-L329

Just iterate over [entrySet](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ConcurrentHashMap.html#entrySet--).

Should also check `ConcurrentHashMap` usages in other places.

**Comment by badgerwithagun** [comment]
Fixing this now

**Comment by badgerwithagun** [comment]
@berserkk, would you be interested in providing your review on #282?

**Comment by berserkk** [comment]
@badgerwithagun, sure, I'll check.
