### ISSUE TITLE
Kraken Web Socket now available

### ISSUE THREAD

**Issue by xpitrus** [bitrich-info/xchange-stream#279]
Kraken web socket is now available. 
https://www.kraken.com/features/websocket-api

Is someone interested in developing a kraken interface? We can compensate for the development.

xpitrus@yahoo.it

Thanks

**Comment by badgerwithagun** [comment]
Which features do you need?

* Ticker
* Trades
* Order book
* Account balances
* Account trades
* Account order updates

**Comment by xpitrus** [comment]
We need the public one:
Ticker
Trades
Order book

**Comment by xpitrus** [comment]
Thanks. The Order book is the one we need the most.

**Comment by xpitrus** [comment]
@badgerwithagun is ok for you to pick this up? Please if ok send me a message via email.

**Comment by badgerwithagun** [comment]
I don't think I have time right now, I'm afraid.  I may do in a few weeks.  In the meantime, hopefully someone else can pick it up.

**Comment by xpitrus** [comment]
Thanks @badgerwithagun. 
Please if others are interested, contact me.

**Comment by AMA2018** [comment]
Hey @xpitrus  I`m interested in Kraken Websocket. I need it pretty soon so I`m thinking about implementing it.

**Comment by xpitrus** [comment]
thanks @AMA2018. Are you working on that? When do you think you can have it ready?

**Comment by AMA2018** [comment]
Hey @xpitrus. We need kraken websocket API in our business but the requirement has been delayed. We dont have the resources to work on that implementation yet. Anyone else able to do this?

**Comment by xpitrus** [comment]
@badgerwithagun some time now? reward still available!

**Comment by badgerwithagun** [comment]
@xpitrus: sorry, still too busy.

**Comment by mdvx** [comment]
I am interested.. How do I take this issue?

**Comment by makarid** [comment]
Hello i am trying to implement the Kraken websocket. But because i don't understand how JsonNettyStreamingService works exactly i am don't know what method i need to implement. Can some just give me a hint about that? If some could implement only the kraken ping pong websocket subscription i would be grateful. Thanks

**Comment by makarid** [comment]
Hello, i have just finished the orderbook of Kraken Stream. Although i haven't test it much, so if someone finds a bug please tell me in order to fix it.Thanks

**Comment by pchertalev** [comment]
@makarid did you create pool request of kraken connector? I was going to create kraken connector by myself, but if you have one, I can help with additional features.

**Comment by pchertalev** [comment]
Hi Guys, I have opened new PR #344 with full Kraken Web Socket implementation. It is fully reworked code of PR #316 from @makarid. I need Kraken Websocket in production as soon as possible, so I would be very glad to see revew comments asap as well :)

**Comment by pchertalev** [comment]
Anyone wants to review it?

**Comment by badgerwithagun** [comment]
Sure, done. As normal, I'm reviewing it only for standards/consistency really.  I'm not checking if the actual Kraken code actually works (I'll leave that to you lot who actually use it).

**Comment by pchertalev** [comment]
xpitrus, please close this issue

**Comment by makarid** [comment]
@pchertalev i have found some inconsistencies with the Kraken orderbook implementation. I am getting prices like 1.033E+4.Also ask prices do not update properly and there isn't any protection when bid is bigger than ask and reverse. Is it possible to fix at least the issue with the prices of 1.033E+4 like?

**Comment by pchertalev** [comment]
Lets close this issue guys?

**Comment by dpisklov** [comment]
@badgerwithagun @dozd 
Guys is it possible to get a release with this fix included? Last release was some 4 months ago and there has been a lot of new stuff which we'd like to use... Pretty please?

**Comment by badgerwithagun** [comment]
Only @dozd can help with releases.

**Comment by dozd** [comment]
Doing it right now!

**Comment by dozd** [comment]
If you know @badgerwithagun what's needed for you to be able to make a release, give me a pm ;). I don't know if you can release a project into maven central with different GPG signature 🤔

**Comment by dpisklov** [comment]
It depends how you make the release. We use an account on [OSS Sonatype Nexus](https://oss.sonatype.org) to create staging repo and then promote it to maven cetral. IIRC it will accept any valid GPG key, but obviously you'd need to share the Sonatype account.

**Comment by badgerwithagun** [comment]
Whether it's worth the effort depends on https://github.com/knowm/XChange/issues/3220.

It sounds like that's veering towards "merge them", in which case our target should be to get as many PRs cleared as we can, do a final release and then start submitting XChange PRs.

**Comment by dpisklov** [comment]
@badgerwithagun I'd support the merge for sure as long as the modularity is maintained (i.e. we only use streaming APIs, and we'd rather have minimal if any dependencies on REST parts)

**Comment by badgerwithagun** [comment]
@dpisklov - dependencies are impossible to avoid (xchange-stream-binance depends on xchange-binance, which depends on xchange-core - that's how they are designed) but in terms of _calling_ REST APIs, yes, in general we try and avoid it except where absolutely necessary (e.g. getting initial snapshots for the order book stream on Binance).

I've specifically resisted letting the trade/account/balance streams get overcomplicated by features like self-correction, because it would mean too much complex use of multiple APIs to get right. I see no reason for that decision to change.

**Comment by dpisklov** [comment]
@badgerwithagun that's fair enough

**Comment by dozd** [comment]
There should be xchange-stream:4.4.0 in central. I will do the github rls later.

**Comment by dpisklov** [comment]
@dozd yes I am using it already - thanks a ton!
