### ISSUE TITLE
Gemini WebSocket disconnect doesn't shutdown nioEventLoopGroup threads

### ISSUE THREAD

**Issue by KeshavSirohi** [bitrich-info/xchange-stream#283]
Gemini disconnect doesn't shutdown nioEventLoopGroup threads. When re-connection(disconnect and then connect) is done, two new nioEventLoopGroup threads gets created. This count keeps on increasing because older threads never shutdown.

**Comment by badgerwithagun** [comment]
Could you try the code on pull request #282?

That tries to be more thorough at shutting down the event loop group in all cases.

**Comment by KeshavSirohi** [comment]
Issue remains with PR 282. I think the issue is in Gemini classes.

**Comment by badgerwithagun** [comment]
I did a full tidy-up of this are in #340.  Looks like it should help.
