### ISSUE TITLE
Binance order book stops recieving data

### ISSUE THREAD

**Issue by Gehazzz** [bitrich-info/xchange-stream#285]
I am trying to recieve binance order book stream.

My code:
```

StreamingExchange exchange = StreamingExchangeFactory.INSTANCE.createExchange(BinanceStreamingExchange.class.getName());
        ProductSubscription subscription = ProductSubscription.create()
                .addOrderbook(CurrencyPair.XRP_BTC)
                .addOrderbook(CurrencyPair.ETH_BTC).build();
        exchange.connect(subscription).blockingAwait();

        exchange.getStreamingMarketDataService().getOrderBook(CurrencyPair.XRP_BTC)
                .subscribe(orderBook -> {

                    System.out.println(orderBook.getAsks().get(0).toString());
                    System.out.println(orderBook.getBids().get(0).toString());

                }, throwable -> {
                    System.out.println("ERROR in getting order book: " + throwable);
                });
        exchange.getStreamingMarketDataService().getOrderBook(CurrencyPair.ETH_BTC)
                .subscribe(orderBook -> {

                    System.out.println(orderBook.getAsks().get(0).toString());
                    System.out.println(orderBook.getBids().get(0).toString());

                }, throwable -> {
                    System.out.println("ERROR in getting order book: " + throwable);
                });
```

After some period of time like 1-15 mins it stops recieving data without any error.
What can be a problem?
Thanks a lot!

**Comment by badgerwithagun** [comment]
- Which version are you using?
 - Could you post a copy of the logs? xchange-stream logs through slf4j so you might need to add a connector to the classpath if you don't have one already.

**Comment by Gehazzz** [comment]
I am using 4.3.14 and I tryed 4.3.11

logs:

> 20:37:01.254 [default] [nioEventLoopGroup-3-1] DEBUG i.n.h.c.h.w.WebSocket08FrameDecoder - Decoding WebSocket Frame opCode=1 
> 20:37:01.254 [default] [nioEventLoopGroup-3-1] DEBUG i.n.h.c.h.w.WebSocket08FrameDecoder - Decoding WebSocket Frame length=22 
> 20:37:01.254 [default] [nioEventLoopGroup-3-1] DEBUG i.n.h.c.h.w.WebSocket08FrameDecoder - Decoding WebSocket Frame opCode=1 
> 20:37:01.254 [default] [nioEventLoopGroup-3-1] DEBUG i.n.h.c.h.w.WebSocket08FrameDecoder - Decoding WebSocket Frame length=24 
> 20:37:01.255 [default] [nioEventLoopGroup-3-1] DEBUG i.n.h.c.h.w.WebSocket08FrameDecoder - Decoding WebSocket Frame opCode=1 
> 20:37:01.255 [default] [nioEventLoopGroup-3-1] DEBUG i.n.h.c.h.w.WebSocket08FrameDecoder - Decoding WebSocket Frame length=23 
> 20:37:01.283 [default] [nioEventLoopGroup-3-1] DEBUG i.n.h.c.h.w.WebSocket08FrameDecoder - Decoding WebSocket Frame opCode=1 
> 20:37:01.283 [default] [nioEventLoopGroup-3-1] DEBUG i.n.h.c.h.w.WebSocket08FrameDecoder - Decoding WebSocket Frame length=22 
> 20:37:01.283 [default] [nioEventLoopGroup-3-1] DEBUG i.n.h.c.h.w.WebSocket08FrameDecoder - Decoding WebSocket Frame opCode=1 
> 20:37:01.283 [default] [nioEventLoopGroup-3-1] DEBUG i.n.h.c.h.w.WebSocket08FrameDecoder - Decoding WebSocket Frame length=22 
> 20:37:01.284 [default] [nioEventLoopGroup-3-1] DEBUG i.n.h.c.h.w.WebSocket08FrameDecoder - Decoding WebSocket Frame opCode=1 
> 20:37:01.284 [default] [nioEventLoopGroup-3-1] DEBUG i.n.h.c.h.w.WebSocket08FrameDecoder - Decoding WebSocket Frame length=22 
> 20:37:01.284 [default] [nioEventLoopGroup-3-1] DEBUG i.n.h.c.h.w.WebSocket08FrameDecoder - Decoding WebSocket Frame opCode=1 
> 20:37:01.284 [default] [nioEventLoopGroup-3-1] DEBUG i.n.h.c.h.w.WebSocket08FrameDecoder - Decoding WebSocket Frame length=20 
> 20:37:01.285 [default] [nioEventLoopGroup-3-1] DEBUG i.n.h.c.h.w.WebSocket08FrameDecoder - Decoding WebSocket Frame opCode=1 
> 20:37:01.285 [default] [nioEventLoopGroup-3-1] DEBUG i.n.h.c.h.w.WebSocket08FrameDecoder - Decoding WebSocket Frame length=22 
> 20:37:01.285 [default] [nioEventLoopGroup-3-1] DEBUG i.n.h.c.h.w.WebSocket08FrameDecoder - Decoding WebSocket Frame opCode=1 
> 20:37:01.285 [default] [nioEventLoopGroup-3-1] DEBUG i.n.h.c.h.w.WebSocket08FrameDecoder - Decoding WebSocket Frame length=22 
> 20:37:01.285 [default] [nioEventLoopGroup-3-1] DEBUG i.n.h.c.h.w.WebSocket08FrameDecoder - Decoding WebSocket Frame opCode=1 
> 20:37:01.285 [default] [nioEventLoopGroup-3-1] DEBUG i.n.h.c.h.w.WebSocket08FrameDecoder - Decoding WebSocket Frame length=30 
> 20:37:01.286 [default] [nioEventLoopGroup-3-1] DEBUG i.n.h.c.h.w.WebSocket08FrameDecoder - Decoding WebSocket Frame opCode=1 
> 20:37:01.286 [default] [nioEventLoopGroup-3-1] DEBUG i.n.h.c.h.w.WebSocket08FrameDecoder - Decoding WebSocket Frame length=22 
> 20:37:01.286 [default] [nioEventLoopGroup-3-1] DEBUG i.n.h.c.h.w.WebSocket08FrameDecoder - Decoding WebSocket Frame opCode=1 
> 20:37:01.286 [default] [nioEventLoopGroup-3-1] DEBUG i.n.h.c.h.w.WebSocket08FrameDecoder - Decoding WebSocket Frame length=22 
> 20:37:01.286 [default] [nioEventLoopGroup-3-1] DEBUG i.n.h.c.h.w.WebSocket08FrameDecoder - Decoding WebSocket Frame opCode=1 
> 20:37:01.286 [default] [nioEventLoopGroup-3-1] DEBUG i.n.h.c.h.w.WebSocket08FrameDecoder - Decoding WebSocket Frame length=31 
> LimitOrder [limitPrice=0.03578300, Order [type=ASK, originalAmount=0.34400000, cumulativeAmount=null, averagePrice=null, currencyPair=ETH/BTC, id=, timestamp=Wed Feb 27 20:36:59 IST 2019, status=null]]
> LimitOrder [limitPrice=0.03577400, Order [type=BID, originalAmount=0.41900000, cumulativeAmount=null, averagePrice=null, currencyPair=ETH/BTC, id=, timestamp=Wed Feb 27 20:36:58 IST 2019, status=null]]
> LimitOrder [limitPrice=0.00008212, Order [type=ASK, originalAmount=1588.00000000, cumulativeAmount=null, averagePrice=null, currencyPair=XRP/BTC, id=, timestamp=Wed Feb 27 20:36:58 IST 2019, status=null]]
> LimitOrder [limitPrice=0.00008208, Order [type=BID, originalAmount=207.00000000, cumulativeAmount=null, averagePrice=null, currencyPair=XRP/BTC, id=, timestamp=Wed Feb 27 20:36:51 IST 2019, status=null]]
> 20:37:31.915 [default] [Catalina-utility-1] DEBUG o.a.catalina.session.ManagerBase - Start expire sessions StandardManager at 1551292651915 sessioncount 0 
> 20:37:31.915 [default] [Catalina-utility-1] DEBUG o.a.catalina.session.ManagerBase - End expire sessions StandardManager processingTime 0 expired sessions: 0 
> 20:38:31.920 [default] [Catalina-utility-1] DEBUG o.a.catalina.session.ManagerBase - Start expire sessions StandardManager at 1551292711920 sessioncount 0 
> 20:38:31.920 [default] [Catalina-utility-1] DEBUG o.a.catalina.session.ManagerBase - End expire sessions StandardManager processingTime 0 expired sessions: 0 
> 20:39:31.925 [default] [Catalina-utility-1] DEBUG o.a.catalina.session.ManagerBase - Start expire sessions StandardManager at 1551292771925 sessioncount 0 
> 20:39:31.925 [default] [Catalina-utility-1] DEBUG o.a.catalina.session.ManagerBase - End expire sessions StandardManager processingTime 0 expired sessions: 0 
> 20:40:31.945 [default] [Catalina-utility-1] DEBUG o.a.catalina.session.ManagerBase - Start expire sessions StandardManager at 1551292831945 sessioncount 0 
> 20:40:31.945 [default] [Catalina-utility-1] DEBUG o.a.catalina.session.ManagerBase - End expire sessions StandardManager processingTime 0 expired sessions: 0 
> 20:41:31.949 [default] [Catalina-utility-1] DEBUG o.a.catalina.session.ManagerBase - Start expire sessions StandardManager at 1551292891949 sessioncount 0 
> 20:41:31.949 [default] [Catalina-utility-1] DEBUG o.a.catalina.session.ManagerBase - End expire sessions StandardManager processingTime 0 expired sessions: 0 
> 20:42:31.955 [default] [Catalina-utility-1] DEBUG o.a.catalina.session.ManagerBase - Start expire sessions StandardManager at 1551292951955 sessioncount 0 
> 20:42:31.955 [default] [Catalina-utility-1] DEBUG o.a.catalina.session.ManagerBase - End expire sessions StandardManager processingTime 0 expired sessions: 0 
> 20:43:31.964 [default] [Catalina-utility-2] DEBUG o.a.catalina.session.ManagerBase - Start expire sessions StandardManager at 1551293011964 sessioncount 0 
> 20:43:31.964 [default] [Catalina-utility-2] DEBUG o.a.catalina.session.ManagerBase - End expire sessions StandardManager processingTime 0 expired sessions: 0 
> 20:44:31.970 [default] [Catalina-utility-1] DEBUG o.a.catalina.session.ManagerBase - Start expire sessions StandardManager at 1551293071970 sessioncount 0 
> 20:44:31.970 [default] [Catalina-utility-1] DEBUG o.a.catalina.session.ManagerBase - End expire sessions StandardManager processingTime 0 expired sessions: 0 
> 20:45:31.977 [default] [Catalina-utility-2] DEBUG o.a.catalina.session.ManagerBase - Start expire sessions StandardManager at 1551293131977 sessioncount 0 
> 20:45:31.978 [default] [Catalina-utility-2] DEBUG o.a.catalina.session.ManagerBase - End expire sessions StandardManager processingTime 0 expired sessions: 0 
> 20:46:31.984 [default] [Catalina-utility-2] DEBUG o.a.catalina.session.ManagerBase - Start expire sessions StandardManager at 1551293191984 sessioncount 0 
> 20:46:31.985 [default] [Catalina-utility-2] DEBUG o.a.catalina.session.ManagerBase - End expire sessions StandardManager processingTime 0 expired sessions: 0

**Comment by badgerwithagun** [comment]
Could you try 4.3.15, please?

Those look like Tomcat manager logs rather than the application log.  I've not used Tomcat for a long time, but I recall it writing two separate logs. Can you see another?

**Comment by Gehazzz** [comment]
Now logs keep running but I do not recieve data:

> 22:07:26.936 [default] [nioEventLoopGroup-4-1] DEBUG i.n.h.c.h.w.WebSocket08FrameDecoder - Decoding WebSocket Frame length=23 
> 22:07:26.936 [default] [nioEventLoopGroup-4-1] DEBUG i.n.h.c.h.w.WebSocket08FrameDecoder - Decoding WebSocket Frame opCode=1 
> 22:07:26.936 [default] [nioEventLoopGroup-4-1] DEBUG i.n.h.c.h.w.WebSocket08FrameDecoder - Decoding WebSocket Frame length=23 
> 22:07:26.937 [default] [nioEventLoopGroup-4-1] DEBUG i.n.h.c.h.w.WebSocket08FrameDecoder - Decoding WebSocket Frame opCode=1 
> 22:07:26.937 [default] [nioEventLoopGroup-4-1] DEBUG i.n.h.c.h.w.WebSocket08FrameDecoder - Decoding WebSocket Frame length=28 
> 22:07:26.937 [default] [nioEventLoopGroup-4-1] DEBUG i.n.h.c.h.w.WebSocket08FrameDecoder - Decoding WebSocket Frame opCode=1 
> 22:07:26.937 [default] [nioEventLoopGroup-4-1] DEBUG i.n.h.c.h.w.WebSocket08FrameDecoder - Decoding WebSocket Frame length=25 
> 22:07:26.937 [default] [nioEventLoopGroup-4-1] DEBUG i.n.h.c.h.w.WebSocket08FrameDecoder - Decoding WebSocket Frame opCode=1 
> 22:07:26.937 [default] [nioEventLoopGroup-4-1] DEBUG i.n.h.c.h.w.WebSocket08FrameDecoder - Decoding WebSocket Frame length=32 
> 22:07:26.949 [default] [Catalina-utility-1] DEBUG o.a.catalina.session.ManagerBase - Start expire sessions StandardManager at 1551298046949 sessioncount 0 
> 22:07:26.949 [default] [Catalina-utility-1] DEBUG o.a.catalina.session.ManagerBase - End expire sessions StandardManager processingTime 0 expired sessions: 0 
> 22:07:26.955 [default] [nioEventLoopGroup-4-1] DEBUG i.n.h.c.h.w.WebSocket08FrameDecoder - Decoding WebSocket Frame opCode=1 
> 22:07:26.955 [default] [nioEventLoopGroup-4-1] DEBUG i.n.h.c.h.w.WebSocket08FrameDecoder - Decoding WebSocket Frame length=18 
> 22:07:26.955 [default] [nioEventLoopGroup-4-1] DEBUG i.n.h.c.h.w.WebSocket08FrameDecoder - Decoding WebSocket Frame opCode=1 
> 22:07:26.955 [default] [nioEventLoopGroup-4-1] DEBUG i.n.h.c.h.w.WebSocket08FrameDecoder - Decoding WebSocket Frame length=18 
> 22:07:26.955 [default] [nioEventLoopGroup-4-1] DEBUG i.n.h.c.h.w.WebSocket08FrameDecoder - Decoding WebSocket Frame opCode=1 
> 22:07:26.955 [default] [nioEventLoopGroup-4-1] DEBUG i.n.h.c.h.w.WebSocket08FrameDecoder - Decoding WebSocket Frame length=18 
> 22:07:26.956 [default] [nioEventLoopGroup-4-1] DEBUG i.n.h.c.h.w.WebSocket08FrameDecoder - Decoding WebSocket Frame opCode=1 
> 22:07:26.956 [default] [nioEventLoopGroup-4-1] DEBUG i.n.h.c.h.w.WebSocket08FrameDecoder - Decoding WebSocket Frame length=20 
> 22:07:27.018 [default] [nioEventLoopGroup-4-1] DEBUG i.n.h.c.h.w.WebSocket08FrameDecoder - Decoding WebSocket Frame opCode=1 
> 22:07:27.018 [default] [nioEventLoopGroup-4-1] DEBUG i.n.h.c.h.w.WebSocket08FrameDecoder - Decoding WebSocket Frame length=25 
> 22:07:27.019 [default] [nioEventLoopGroup-4-1] DEBUG i.n.h.c.h.w.WebSocket08FrameDecoder - Decoding WebSocket Frame opCode=1 
> 22:07:27.019 [default] [nioEventLoopGroup-4-1] DEBUG i.n.h.c.h.w.WebSocket08FrameDecoder - Decoding WebSocket Frame length=36 
> 22:07:27.020 [default] [nioEventLoopGroup-4-1] DEBUG i.n.h.c.h.w.WebSocket08FrameDecoder - Decoding WebSocket Frame opCode=1 
> 22:07:27.020 [default] [nioEventLoopGroup-4-1] DEBUG i.n.h.c.h.w.WebSocket08FrameDecoder - Decoding WebSocket Frame length=20

**Comment by Gehazzz** [comment]
After several time I got this:

> 22:37:20.318 [default] [nioEventLoopGroup-3-1] DEBUG i.n.h.c.h.w.WebSocket08FrameDecoder - Decoding WebSocket Frame opCode=1 
> 22:37:20.318 [default] [nioEventLoopGroup-3-1] DEBUG i.n.h.c.h.w.WebSocket08FrameDecoder - Decoding WebSocket Frame length=22 
> 22:37:20.318 [default] [nioEventLoopGroup-3-1] DEBUG i.n.h.c.h.w.WebSocket08FrameDecoder - Decoding WebSocket Frame opCode=1 
> 22:37:20.318 [default] [nioEventLoopGroup-3-1] DEBUG i.n.h.c.h.w.WebSocket08FrameDecoder - Decoding WebSocket Frame length=32 
> 22:37:20.319 [default] [nioEventLoopGroup-3-1] DEBUG i.n.h.c.h.w.WebSocket08FrameDecoder - Decoding WebSocket Frame opCode=1 
> 22:37:20.319 [default] [nioEventLoopGroup-3-1] DEBUG i.n.h.c.h.w.WebSocket08FrameDecoder - Decoding WebSocket Frame length=22 
> 22:37:20.319 [default] [nioEventLoopGroup-3-1] DEBUG i.n.h.c.h.w.WebSocket08FrameDecoder - Decoding WebSocket Frame opCode=1 
> 22:37:20.319 [default] [nioEventLoopGroup-3-1] DEBUG i.n.h.c.h.w.WebSocket08FrameDecoder - Decoding WebSocket Frame length=33 
> 22:37:20.319 [default] [nioEventLoopGroup-3-1] DEBUG i.n.h.c.h.w.WebSocket08FrameDecoder - Decoding WebSocket Frame opCode=1 
> 22:37:20.319 [default] [nioEventLoopGroup-3-1] DEBUG i.n.h.c.h.w.WebSocket08FrameDecoder - Decoding WebSocket Frame length=24 
> 22:37:20.319 [default] [nioEventLoopGroup-3-1] DEBUG i.n.h.c.h.w.WebSocket08FrameDecoder - Decoding WebSocket Frame opCode=1 
> 22:37:20.319 [default] [nioEventLoopGroup-3-1] DEBUG i.n.h.c.h.w.WebSocket08FrameDecoder - Decoding WebSocket Frame length=29 
> 22:37:20.319 [default] [nioEventLoopGroup-3-1] DEBUG i.n.h.c.h.w.WebSocket08FrameDecoder - Decoding WebSocket Frame opCode=1 
> 22:37:20.319 [default] [nioEventLoopGroup-3-1] DEBUG i.n.h.c.h.w.WebSocket08FrameDecoder - Decoding WebSocket Frame length=38 
> 22:37:52.695 [default] [Catalina-utility-1] DEBUG o.a.catalina.session.ManagerBase - Start expire sessions StandardManager at 1551299872695 sessioncount 0 
> 22:37:52.695 [default] [Catalina-utility-1] DEBUG o.a.catalina.session.ManagerBase - End expire sessions StandardManager processingTime 0 expired sessions: 0 
> 22:38:52.703 [default] [Catalina-utility-2] DEBUG o.a.catalina.session.ManagerBase - Start expire sessions StandardManager at 1551299932703 sessioncount 0 
> 22:38:52.703 [default] [Catalina-utility-2] DEBUG o.a.catalina.session.ManagerBase - End expire sessions StandardManager processingTime 0 expired sessions: 0 
> 22:39:52.711 [default] [Catalina-utility-2] DEBUG o.a.catalina.session.ManagerBase - Start expire sessions StandardManager at 1551299992711 sessioncount 0 
> 22:39:52.711 [default] [Catalina-utility-2] DEBUG o.a.catalina.session.ManagerBase - End expire sessions StandardManager processingTime 0 expired sessions: 0 
> 22:40:52.716 [default] [Catalina-utility-2] DEBUG o.a.catalina.session.ManagerBase - Start expire sessions StandardManager at 1551300052716 sessioncount 0 
> 22:40:52.716 [default] [Catalina-utility-2] DEBUG o.a.catalina.session.ManagerBase - End expire sessions StandardManager processingTime 0 expired sessions: 0 
> 22:41:52.723 [default] [Catalina-utility-2] DEBUG o.a.catalina.session.ManagerBase - Start expire sessions StandardManager at 1551300112723 sessioncount 0 
> 22:41:52.723 [default] [Catalina-utility-2] DEBUG o.a.catalina.session.ManagerBase - End expire sessions StandardManager processingTime 0 expired sessions: 0 
> 22:42:52.730 [default] [Catalina-utility-2] DEBUG o.a.catalina.session.ManagerBase - Start expire sessions StandardManager at 1551300172730 sessioncount 0 
> 22:42:52.730 [default] [Catalina-utility-2] DEBUG o.a.catalina.session.ManagerBase - End expire sessions StandardManager processingTime 0 expired sessions: 0 
> 22:43:52.736 [default] [Catalina-utility-2] DEBUG o.a.catalina.session.ManagerBase - Start expire sessions StandardManager at 1551300232736 sessioncount 0 
> 22:43:52.736 [default] [Catalina-utility-2] DEBUG o.a.catalina.session.ManagerBase - End expire sessions StandardManager processingTime 0 expired sessions: 0 
> 22:44:52.743 [default] [Catalina-utility-1] DEBUG o.a.catalina.session.ManagerBase - Start expire sessions StandardManager at 1551300292743 sessioncount 0 
> 22:44:52.744 [default] [Catalina-utility-1] DEBUG o.a.catalina.session.ManagerBase - End expire sessions StandardManager processingTime 0 expired sessions: 0 
> 22:45:52.752 [default] [Catalina-utility-1] DEBUG o.a.catalina.session.ManagerBase - Start expire sessions StandardManager at 1551300352752 sessioncount 0 
> 22:45:52.753 [default] [Catalina-utility-1] DEBUG o.a.catalina.session.ManagerBase - End expire sessions StandardManager processingTime 1 expired sessions: 0 
> 22:46:52.762 [default] [Catalina-utility-2] DEBUG o.a.catalina.session.ManagerBase - Start expire sessions StandardManager at 1551300412762 sessioncount 0 
> 22:46:52.763 [default] [Catalina-utility-2] DEBUG o.a.catalina.session.ManagerBase - End expire sessions StandardManager processingTime 0 expired sessions: 0 
> 22:47:52.768 [default] [Catalina-utility-1] DEBUG o.a.catalina.session.ManagerBase - Start expire sessions StandardManager at 1551300472768 sessioncount 0 
> 22:47:52.768 [default] [Catalina-utility-1] DEBUG o.a.catalina.session.ManagerBase - End expire sessions StandardManager processingTime 0 expired sessions: 0 
> 22:48:52.776 [default] [Catalina-utility-1] DEBUG o.a.catalina.session.ManagerBase - Start expire sessions StandardManager at 1551300532776 sessioncount 0 
> 22:48:52.776 [default] [Catalina-utility-1] DEBUG o.a.catalina.session.ManagerBase - End expire sessions StandardManager processingTime 0 expired sessions: 0 
> 22:49:52.785 [default] [Catalina-utility-1] DEBUG o.a.catalina.session.ManagerBase - Start expire sessions StandardManager at 1551300592785 sessioncount 0 
> 22:49:52.785 [default] [Catalina-utility-1] DEBUG o.a.catalina.session.ManagerBase - End expire sessions StandardManager processingTime 0 expired sessions: 0 
> 22:50:52.792 [default] [Catalina-utility-2] DEBUG o.a.catalina.session.ManagerBase - Start expire sessions StandardManager at 1551300652792 sessioncount 0 
> 22:50:52.793 [default] [Catalina-utility-2] DEBUG o.a.catalina.session.ManagerBase - End expire sessions StandardManager processingTime 0 expired sessions: 0 
> 22:51:52.796 [default] [Catalina-utility-1] DEBUG o.a.catalina.session.ManagerBase - Start expire sessions StandardManager at 1551300712796 sessioncount 0 
> 22:51:52.796 [default] [Catalina-utility-1] DEBUG o.a.catalina.session.ManagerBase - End expire sessions StandardManager processingTime 0 expired sessions: 0 
> 22:52:52.803 [default] [Catalina-utility-1] DEBUG o.a.catalina.session.ManagerBase - Start expire sessions StandardManager at 1551300772803 sessioncount 0 
> 22:52:52.804 [default] [Catalina-utility-1] DEBUG o.a.catalina.session.ManagerBase - End expire sessions StandardManager processingTime 0 expired sessions: 0 
> 22:53:52.810 [default] [Catalina-utility-2] DEBUG o.a.catalina.session.ManagerBase - Start expire sessions StandardManager at 1551300832810 sessioncount 0 
> 22:53:52.810 [default] [Catalina-utility-2] DEBUG o.a.catalina.session.ManagerBase - End expire sessions StandardManager processingTime 0 expired sessions: 0 
> 22:54:52.818 [default] [Catalina-utility-2] DEBUG o.a.catalina.session.ManagerBase - Start expire sessions StandardManager at 1551300892818 sessioncount 0 
> 22:54:52.818 [default] [Catalina-utility-2] DEBUG o.a.catalina.session.ManagerBase - End expire sessions StandardManager processingTime 0 expired sessions: 0 
> 22:55:52.824 [default] [Catalina-utility-2] DEBUG o.a.catalina.session.ManagerBase - Start expire sessions StandardManager at 1551300952824 sessioncount 0 
> 22:55:52.824 [default] [Catalina-utility-2] DEBUG o.a.catalina.session.ManagerBase - End expire sessions StandardManager processingTime 0 expired sessions: 0 
> 22:56:52.831 [default] [Catalina-utility-1] DEBUG o.a.catalina.session.ManagerBase - Start expire sessions StandardManager at 1551301012831 sessioncount 0 
> 22:56:52.832 [default] [Catalina-utility-1] DEBUG o.a.catalina.session.ManagerBase - End expire sessions StandardManager processingTime 0 expired sessions: 0

**Comment by dpisklov** [comment]
@Gehazzz it takes its time it seems.
For me it takes good minute until it starts ticking, smapping this kind of stuff:

```
[nioEventLoopGroup-2-1] DEBUG si.mazi.rescu.HttpTemplate - Executing GET request at https://api.binance.com/api/v1/depth?symbol=ETHUSDT&limit=1000
[nioEventLoopGroup-2-1] DEBUG si.mazi.rescu.HttpTemplate - Request http status = 200
[nioEventLoopGroup-2-1] DEBUG io.netty.handler.codec.http.websocketx.WebSocket08FrameDecoder - Decoding WebSocket Frame opCode=1
[nioEventLoopGroup-2-1] DEBUG io.netty.handler.codec.http.websocketx.WebSocket08FrameDecoder - Decoding WebSocket Frame length=90
[nioEventLoopGroup-2-1] DEBUG info.bitrich.xchangestream.service.netty.JsonNettyStreamingService - Received message: {"stream":"ethusdt@ticker","data":{"e":"24hrTicker","E":1552067434903,"s":"ETHUSDT","p":"0.07000000","P":"0.051","w":"136.76083624","x":"136.93000000","c":"136.99000000","Q":"7.30226000","b":"136.96000000","B":"6.42599000","a":"136.97000000","A":"2.34319000","o":"136.92000000","h":"138.28000000","l":"135.17000000","v":"242311.15632000","q":"33138676.36764450","O":1551981034897,"C":1552067434897,"F":64452059,"L":64546027,"n":93969}}
[nioEventLoopGroup-2-1] DEBUG io.netty.handler.codec.http.websocketx.WebSocket08FrameDecoder - Decoding WebSocket Frame opCode=1
[nioEventLoopGroup-2-1] DEBUG io.netty.handler.codec.http.websocketx.WebSocket08FrameDecoder - Decoding WebSocket Frame length=73
[nioEventLoopGroup-2-1] DEBUG info.bitrich.xchangestream.service.netty.JsonNettyStreamingService - Received message: {"stream":"ethusdt@depth","data":{"e":"depthUpdate","E":1552067435424,"s":"ETHUSDT","U":328609266,"u":328609273,"b":[["136.96000000","6.42599000",[]],["136.93000000","0.00000000",[]],["136.90000000","0.00000000",[]],["136.88000000","0.00000000",[]]],"a":[["136.97000000","2.34319000",[]],["136.98000000","4.00000000",[]],["136.99000000","21.17974000",[]],["137.06000000","0.00000000",[]]]}}
[nioEventLoopGroup-2-1] INFO info.bitrich.xchangestream.binance.BinanceStreamingMarketDataService - Orderbook snapshot for ETH/USDT out of date (last=328609269, U=328609266, u=328609273). This is normal. Re-syncing.
[nioEventLoopGroup-2-1] DEBUG io.netty.handler.codec.http.websocketx.WebSocket08FrameDecoder - Decoding WebSocket Frame opCode=1
[nioEventLoopGroup-2-1] DEBUG io.netty.handler.codec.http.websocketx.WebSocket08FrameDecoder - Decoding WebSocket Frame length=46
```

@badgerwithagun the not-so-good thing here is, in my case, I only need orderbook, but the code subscribes to ticker and trades too, just in case. Not sure if there's a simple way around it...

**Comment by badgerwithagun** [comment]
@dpisklov - aha, that's better, looks more like actual xchange-stream logs. 

It shouldn't subscribe to any more than you ask for.  In the [example](https://github.com/bitrich-info/xchange-stream/blob/develop/xchange-binance/src/test/java/info/bitrich/xchangestream/binance/BinanceManualExample.java) you notice that a `ProductSubscription` is set up at the beginning specifying what you need when the socket is opened.  If you only include an order book in that, that's all we will request from Binance.

I'm still not sure what the logs are that you're posting, @Gehazzz. Are you sure you have a Slf4j binding so that xchange-stream actually knows where to write the logs?

**Comment by badgerwithagun** [comment]
Oh, also, @dpisklov, I'm not sure if the amount of logging is a problem for you or not, but configuring your logging implementation with a log level of `INFO` will reduce the spam significantly.

**Comment by dpisklov** [comment]
@badgerwithagun nah I'm not bothered about logging ATM, I prefer to see what's going on :)
thanks for the pointer - I was using ProductSubscription but did addAll as seen in CoinbasePro example - didn't even check if it has other parameters, silly bill me :( Works much better now for me - it seems depending on the number of subscriptions things are getting slower and initial snapshot sync simply times out or something. Now I only subscribe to orderbook I start getting updates almost immediately, so I'm good

**Comment by badgerwithagun** [comment]
Great, glad that's working.

**Comment by badgerwithagun** [comment]
@Gehazzz, have you fixed the problem?  If so, I'll close this issue.

**Comment by badgerwithagun** [comment]
Closing - question answered
