### ISSUE TITLE
4.3.0-SNAPSHOT will fail to build in SBT because of javax.ws.rs-api dependency

### ISSUE THREAD

**Issue by awsfanatic** [bitrich-info/xchange-stream#32]
[With an empty .ivy2 cache] SBT will fail to build 4.3.0-SNAPSHOT. Example:

```scala
name := "test"

version := "1.0"

scalaVersion := "2.12.1"

resolvers += "Sonatype OSS Snapshots" at "https://oss.sonatype.org/content/repositories/snapshots"

val xchangeStreamVersion = "4.3.0-SNAPSHOT"

libraryDependencies += "info.bitrich.xchange-stream" % "xchange-stream-core" % xchangeStreamVersion
libraryDependencies += "info.bitrich.xchange-stream" % "xchange-poloniex2" % xchangeStreamVersion
```

Error:
```
[warn] 	[NOT FOUND  ] javax.ws.rs#javax.ws.rs-api;2.1!javax.ws.rs-api.${packaging.type} (1ms)
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/javax/ws/rs/javax.ws.rs-api/2.1/javax.ws.rs-api-2.1.${packaging.type}
```

Looking at https://mvnrepository.com/artifact/javax.ws.rs/javax.ws.rs-api/2.1 I kinda understand why. There is actually `${packaging.type}` in files instead of `jar`. So it's most likely a javax.ws.rs-api issue. Meanwhile you can use a workaround in `build.sbt`:

```scala
val workaround = {
  sys.props += "packaging.type" -> "jar"
  ()
}
```

I was wandering if there is a better way?

**Comment by dozd** [comment]
I actually don't know anything about SBT so if this issue can't be reproduced in Maven, I cannot help you there :-(.

**Comment by dozd** [comment]
Just check [Xchange](https://github.com/timmolter/XChange) library because that dependency is from there.

**Comment by awsfanatic** [comment]
Thanks, I'll move it to Xchange.

**Comment by dozd** [comment]
Like if it's failing alone, than yes :). It was just hint ;).
