### ISSUE TITLE
What happens when websocket gets disconnected?

### ISSUE THREAD

**Issue by andrewlin0410** [bitrich-info/xchange-stream#323]
So I am streaming data from binance I wonder what happens when it disconnects by accident. Is a throwable gonna be throne? Is the library gonna try to reconnect or do I need to do something about it?
Thanks

**Comment by badgerwithagun** [comment]
You might miss messages while the connection is down, though. The order book for Binance will resynchronize itself automatically, but not all exchange implementations do the same thing.  You need to build in resilience in other ways if you can't risk missing trades, for example.

**Comment by badgerwithagun** [comment]
Closing - question answered
