### ISSUE TITLE
Is Binance websocket refresh rate about 1 second?

### ISSUE THREAD

**Issue by andrewlin0410** [bitrich-info/xchange-stream#345]
It seems the ticker observable makes a new ticker around every 1 second. Am I doing this in the wrong way? I was under the impression that websocket should be instant? Is there a fix?
Thanks in advance

**Comment by badgerwithagun** [comment]
That's just what Binance's websocket does.

**Comment by andrewlin0410** [comment]
Do you think implementing multiple websockets for the same data would be a viable option. Maybe that way the update time could be less than 1 second?

**Comment by andrewlin0410** [comment]
I am not asking you guys to do this. I am asking if I should/can.

**Comment by badgerwithagun** [comment]
It all depends on whether Binance runs a single update tick for all connected sockets or per socket. I think there's a good chance it's per-socket or at least per server node. A single global tick wouldnt scale.

Try it!

**Comment by badgerwithagun** [comment]
Don't try just once - try many times. Binance might connect you twice to the same node or to two different nodes. It'd be random.

**Comment by badgerwithagun** [comment]
Closing this @andrewlin0410.  Feel free to re-open if you have any more questions in this area.
