### ISSUE TITLE
 how to use getOrderBook with Binance?

### ISSUE THREAD

**Issue by willll** [bitrich-info/xchange-stream#353]
Hi,

I am trying to retrieve orderbooks from binance, but it keeps returning a nullPointerException :

    ProductSubscriptionBuilder subscriptionBuilder = ProductSubscription.create();
    ProductSubscription subscription = subscriptionBuilder.build();
    streamingExchange.getStreamingMarketDataService()
        .getOrderBook(CurrencyPair.LTC_BTC)
        .subscribe(orderBook -> {
        	logger.info(
                "Order Book ({}): askDepth={} ask={} askSize={} bidDepth={}. bid={}, bidSize={}"
            );
    }, throwable -> logger.error("ERROR in getting order book: ", throwable));

I also tried :
 
    streamingExchange.getStreamingMarketDataService().getOrderBook(c).subscribe(orderBook -> {
        logger.info("OB :" + c.toString() + " " + (orderBook.toString()));
	}, throwable -> {
				// Bleh bleh
        });

What is the right way ?

**Comment by badgerwithagun** [comment]
You need to:

* Connect first
* Subscribe to the currency air on connection

See [BinanceManualExample](https://github.com/bitrich-info/xchange-stream/blob/develop/xchange-binance/src/test/java/info/bitrich/xchangestream/binance/BinanceManualExample.java).

**Comment by badgerwithagun** [comment]
Closing. Fell free to re-open if you have more questions.
