### ISSUE TITLE
Can't use 4.3.17-SNAPSHOT BitfinexStreamingExchange with XChange versions after 4.3.20

### ISSUE THREAD

**Issue by cymp** [bitrich-info/xchange-stream#398]
Hello,

BitfinexStreamingExchange.java has "import org.knowm.xchange.bitfinex.v1.BitfinexExchange;", which does not exist in latest versions of XChange after 4.3.20.

I am confused, I don't know if I should make a PR changing the xchange-stream dependency to XChange from 20 to 22, or if some other way to go is planned to handle this. The problem is I don't want to use too old versions of Xchange.

Thanks

**Comment by makarid** [comment]
Hello, i have update the Xchange version to 21 with my latest PR. When someone approves it, then it will be merged.

**Comment by badgerwithagun** [comment]
Looks like this can be closed.  Please re-open if there are still issues.
