### ISSUE TITLE
[Proposal] Merge this project with knowm/xchange project in order to have one project to work with

### ISSUE THREAD

**Issue by makarid** [bitrich-info/xchange-stream#401]
Hello, i would like to make a proposal to"merge" this project (bitrich-info) with knowm/Xchange project, in order to have only one project to work with.This will kill any version issues, delayed PRs and approvals. I believe it will simplify our work and will create one excellent library with many developers contributing to it. Can we please discuss that?

**Comment by badgerwithagun** [comment]
It's been discussed in the past (although I can't recall where).

The XChange project doesn't want the code merged. The streaming behaviour adds a lot of additional complications.

**Comment by makarid** [comment]
It's a shame.
