### ISSUE TITLE
Build problems with current tree

### ISSUE THREAD

**Issue by arass** [bitrich-info/xchange-stream#436]
running 
mvn package
from the root tree

it gets quite a bit into it then explodes with:
**[ERROR]** /G:/comp/xchange-stream-develop/xchange-bitfinex/src/main/java/info/bitrich/xchangestream/bitfinex/BitfinexStreamingService.java:[31,22] package javax.xml.bind does not exist
**[ERROR]** /G:/comp/xchange-stream-develop/xchange-bitfinex/src/main/java/info/bitrich/xchangestream/bitfinex/BitfinexStreamingService.java:[314,25] cannot find symbol
**[ERROR]**   symbol:   variable DatatypeConverter
**[ERROR]**   location: class info.bitrich.xchangestream.bitfinex.BitfinexStreamingService

Caused by removal of Jaxb from Java 9 and after. 
Need to add this to the pom.xml:

```
 <dependency>    
  <groupId>javax.xml.bind</groupId>  
  <artifactId>jaxb-api</artifactId>   
 <version>2.3.1</version>
</dependency>
```
I recommend around line 155.

**Comment by arass** [comment]
Pull Request waiting for a merge with a fix. 
https://github.com/bitrich-info/xchange-stream/pull/437

**Comment by badgerwithagun** [comment]
Merged.
