### ISSUE TITLE
Including busy spin into example code

### ISSUE THREAD

**Issue by GlebYarnykh** [bitrich-info/xchange-stream#44]
Hi, Im new to RxJava and have some difficulties to understand how it works

In your example, if I try to run the app, I do not get any output. However, if I include while (true) {} before disconnect, I start getting live trades while busy spinning. Is it correct way to implement such applications? When can one read some examples? RxJava docs does not help much honestly

Thanks a lot

**Comment by dozd** [comment]
Yes, it is one way how to implement it. It's like your main application thread cannot end (because it will end all other threads). Better to active looping is for example `Thread.sleep` like in Manual test examples in the source code of the library.
