### ISSUE TITLE
References/examples for building live feed

### ISSUE THREAD

**Issue by nitzanav** [bitrich-info/xchange-stream#45]
Hi,

I want to thank you for this great addition to the XChange project, streaming is jsut what I was looking for :) So THANK YOU.

I want to build a live feed of crypto currencies order book, maybe using a deamon that is similar to what was done in [bitcoinium.com](https://github.com/veken0m/bitcoinium/blob/a60fee461405174ef82bcca89fefcb430baeb368/src/main/java/com/xeiam/tasks/GeneralUpdateDeamon.java#L25) just with sub seconds(100ms is great) pulling time interval.

I want to describe to you my plan and ask for additional references or tips. 

So my plan is:

1. Loop for forever each exchange and symbol
2. If it has WebSocket Api, use [xchange-stream](https://github.com/bitrich-info/xchange-stream) otherwise use REST with [XChange](https://github.com/timmolter/XChange).
3. Retry with some exponential backoff sleeping when  you have a connection error or reached an API rate limit. Like in the [RetriesDemo](https://github.com/timmolter/XChange/blob/0af6279f52d779b324dfce4f4a710952e2ccb166/xchange-examples/src/main/java/org/knowm/xchange/examples/core/utils/RetriesDemo.java). I Guess that I will need to form IPredicate for each exchange, did anyone do it so far?

I would be happy to get input if people here think that my plan is correct and be shared with references of code any relevant example.

What is the right place for such questions?

**Comment by dozd** [comment]
As this is purely general programming question, I'd advice you to use for example stackoverflow.com or similar site. I cannot help you as your question is not concerned about library use nor bug in the library.

Your plan seems correct but the complexity is always in the detail ;-).

**Comment by nitzanav** [comment]
ok 10x.
