### ISSUE TITLE
All modules need renaming ahead of XChange merge

### ISSUE THREAD

**Issue by badgerwithagun** [bitrich-info/xchange-stream#464]
`service-xxx` should be renamed `xchange-stream-service-xxx`
`xchange-xxx` should be renamed `xchange-stream-xxx`

This will namespace the modules appropriately and avoid clash with existing XChange libraries.

**Comment by makarid** [comment]
I will do that

**Comment by TSavo** [comment]
#523 and #524 are ready for merge (one at a time, as one will break the other). These should close this issue and move the ball down the field wrt the xchange merge.
