### ISSUE TITLE
BitFinex ticker API - incorrect symbol value for DASH

### ISSUE THREAD

**Issue by janakerman** [bitrich-info/xchange-stream#48]
When subscribing for the pair `DASH/BTC` from the BitFinex ticker, an `symbol: invalid` response is received. (This actually results in a `NullPointerException` but that is a separate issue.)

This is the request message that is sent out:
```{"event":"subscribe","channel":"ticker","pair":"DASHBTC","prec":null,"len":null}```

This is the response received:
```{"channel":"ticker","pair":"ASHBTC","event":"error","symbol":"DASHBTC","msg":"symbol: invalid","code":10300}```

When you play with the BitFinex's websocket API on their [websocket playground](https://bitfinex.readme.io/v2/reference), it behaves the same, but when you use the pair `DSH/BTC` it starts to send updates. I can only assume that this is DASH as the base, because their `/symbols` API doesn't work as advertised.

Looks like BitFinex API simply expects a different currency symbol that the `Currency` - probably just a configuration update for that exchanges meta data json file?

**Comment by dozd** [comment]
Meta data json files are taken from Xchange library so if it's the fix you must propose a PR there.

**Comment by janakerman** [comment]
Good point - I'll raise it there instead.

**Comment by electic** [comment]
Was there a resolution to this @janakerman? Did you figure it out?

**Comment by janakerman** [comment]
@electic - I haven't submitted a ticket specifically for this instance, but I have raised one for a [similar scenario](https://github.com/timmolter/XChange/issues/2158).

Also BitFinex's [symbol's API](https://api.bitfinex.com/v1/symbols) is now working as expected and shows the following pairs in the response:
```
"dshusd",
"dshbtc",
```

XChange's Bitfinex metadata doesn't have these pairs, so that's the problem I think. Haven't had the time to verify though.

**Comment by nonlinear5** [comment]
I have the same issue, with additional pairs:

Received message: {"channel":"book","pair":"ASHBTC","prec":"R0","len":"100","event":"error","symbol":"DASHBTC","msg":"symbol: invalid","code":10300}
Received message: {"channel":"book","pair":"ASHUSD","prec":"R0","len":"100","event":"error","symbol":"DASHUSD","msg":"symbol: invalid","code":10300}
Received message: {"channel":"book","pair":"CCBTC","prec":"R0","len":"100","event":"error","symbol":"BCCBTC","msg":"symbol: invalid","code":10300}
Received message: {"channel":"book","pair":"CCUSD","prec":"R0","len":"100","event":"error","symbol":"BCCUSD","msg":"symbol: invalid","code":10300}
Received message: {"channel":"book","pair":"CUBTC","prec":"R0","len":"100","event":"error","symbol":"BCUBTC","msg":"symbol: invalid","code":10300}
Received message: {"channel":"book","pair":"CUUSD","prec":"R0","len":"100","event":"error","symbol":"BCUUSD","msg":"symbol: invalid","code":10300}
