### ISSUE TITLE
Differentiate between live orders and trades?

### ISSUE THREAD

**Issue by hwiceberg** [bitrich-info/xchange-stream#5]
For the Bitstamp implementation, the current getTrades() method returns the live orders information. However Bitstamp does have an api for the [live trades](https://www.bitstamp.net/s/examples/live_trades.html). I have tested it, which works fine. Do you think it's a good idea to differentiate these two at the top level abstraction (StreamingMarketDataService)? or Can you suggest some workaround? I am happy to contribute either way.

**Comment by dozd** [comment]
I think it's more of live tickers (according to their documentation - https://www.bitstamp.net/websocket/), isn't it? So I suggest to implement method `getTicker()` in `BitstampStreamingMarketDataService`.

**Comment by dozd** [comment]
Sorry I'm being wrong. You're right. Implementation of `getTrades` in `BitstampStreamingMarketDataService` should call endpoint you mentioned.

**Comment by hwiceberg** [comment]
Thanks for the timely reply. I can change the `getTrades` to call the trade endpoint for now. Do you want to me to create a pull request for that?

**Comment by dozd** [comment]
Sure, go ahead :)

**Comment by dozd** [comment]
Closed by #6
