### ISSUE TITLE
Incorrect timestamp on BitFinex ticker

### ISSUE THREAD

**Issue by janakerman** [bitrich-info/xchange-stream#50]
Timestamps on BitFinex ticker is incorrect. The API isn't returning a timestamp and is being given the current system time in `BitfinexWebSocketTickerTransaction:35`
`float timestamp = System.currentTimeMillis(); //float!?`

Later, this is being multiplied by 1000 in `BitfinexAdaptors::238`:
`Date timestamp = DateUtils.fromMillisUtc((long) (bitfinexTicker.getTimestamp() * 1000L));`

If XStream is expecting a "to the second" timestamp in it's adaptor then `BitfinexWebSocketTickerTransaction` should probably take that into account and `/` by 1000.

Happy to make a PR here - is there anything I should watch out for? E.g other routes that depend on this in millis.

**Comment by alphafoobar** [comment]
I noticed similar issue in order book, created PR #47. But seems more cases need consideration.

**Comment by dozd** [comment]
#47 is merged. Is this fixed?

**Comment by alphafoobar** [comment]
Hi @dozd @janakerman 

Unfortunately my PR did not address the issue described by Jan. Created PR #52

**Comment by janakerman** [comment]
Thanks for putting up that PR @alphafoobar - I do wonder whether we will see this in even more places and should be converting our dates from XChange-Stream time to XChange time in one location?

**Comment by dozd** [comment]
@alphafoobar Cool, thanks!
