### ISSUE TITLE
XChange 4.4.1 has been released

### ISSUE THREAD

**Issue by pchertalev** [bitrich-info/xchange-stream#510]
XChange 4.4.1 has been released, develop version is 4.4.2-SNAPSHOT for now.
Guys, are we going to release XChange-stream 4.4.1 as well?
@badgerwithagun @dozd

**Comment by mdvx** [comment]
any chance we can move up to XChange 4.4.2-SNAPSHOT?
Is there a chatroom for us to discuss these issues?
@badgerwithagun @dozd

**Comment by pchertalev** [comment]
I'm developing Kraken Futures API at the moment and I need to add some XChange changes as well - but versions are different xchange-stream (4.4.1-SNAPSHOT) vs xchange (4.4.2-SNAPSHOT)

**Comment by pchertalev** [comment]
@badgerwithagun @dozd

**Comment by badgerwithagun** [comment]
There's nothing I can do. All PR merging is currently blocked because of a travis issue and I don't have the access necessary to bypass it. Waiting on @dozd.

**Comment by dozd** [comment]
Uf missed this one. I will solve that tomorrow.

**Comment by dozd** [comment]
@badgerwithagun I increased your access so you can bypass whatever you need. I'll solve that travis tomorrow though

**Comment by TSavo** [comment]
Any update on this? I sent an email to @badgerwithagun regarding taking over the maintainer role, I would love to take a more active role in moving this rapidly forward.

**Comment by dozd** [comment]
@badgerwithagun are we good? I see builds on travis.

**Comment by dozd** [comment]
Or you wanna me release develop under 4.4.1 and prepare for the next iteration?

**Comment by badgerwithagun** [comment]
Hey @dozd, yeah I've got on top of the PRs now!

A 4.4.1 release would be good, then sure, we can bump master to 4.4.2-SNAPSHOT.

**Comment by badgerwithagun** [comment]
Hey @TSavo, sorry I've not replied directly to your message. I refer you to this thread: https://github.com/knowm/XChange/issues/3220 in which it was agreed to merge xchange-stream into XChange itself.

To make that happen we really need help getting the project tidied up and prepared for a repository merge, and a plan for how to make the merge work cleanly.   We'd need some good quality PRs and a bit of history with the project before adding a new maintainer (especially after the merge with XChange) so If you could fire some PRs through to help with this, that would be greatly appreciated.

**Comment by TSavo** [comment]
You got it! :)

**Comment by badgerwithagun** [comment]
@dozd: xchange 4.4.2-SNAPSHOT has breaking changes and breaks xchange-stream. I am working on a PR to fix these and bump the dependency, which I'll put up shortly. If you could create the 4.4.1 release first, that'd be great.

**Comment by TSavo** [comment]
@badgerwithagun @dozd PR #525 bumps the version to 4.4.2 and fixes the breaking API changes.

**Comment by badgerwithagun** [comment]
@dozd ok, that PR (#529) is ready to go when the release is done.

**Comment by dozd** [comment]
Releasing right now!

**Comment by badgerwithagun** [comment]
Thanks @dozd.  Updated to 4.4.2-SNAPSHOT now. Closing this.
