### ISSUE TITLE
Exchange specific artifacts for 4.4.2 not on Maven Central

### ISSUE THREAD

**Issue by camodude009** [bitrich-info/xchange-stream#564]
xchange-stream-core:4.4.2 is available (see https://search.maven.org/search?q=a:xchange-stream-core)
The specific exchanges, e.g. xchange-binance:4.4.2 is not (see https://search.maven.org/search?q=a:xchange-binance)

As 4.4.2 was released, I would expect all the exchanges to be released aswell or am I missing something?

**Comment by badgerwithagun** [comment]
They've been renamed: https://search.maven.org/search?q=a:xchange-stream-binance

**Comment by camodude009** [comment]
Thanks, should have thought of that, especially with talks about merging!

**Comment by badgerwithagun** [comment]
No worries!
