### ISSUE TITLE
Can't subscribe on ticker after unsubscription

### ISSUE THREAD

**Issue by KateKom** [bitrich-info/xchange-stream#67]
Hi,
If subscribe on ticker for currency pair once, everthing will work fine, but if unsubscribe and try to subscribe again, nothing  will happen. 
I've tried to get ticker from Bitfinex in such way and after currency pair was unsubscribed and then was subscribed again there were no more tickers. 
I guess it is bug in NettyStreamingService. For my point of view, there is wrong condition check at doOnDispose. 
````
public Observable<T> subscribeChannel(String channelName, Object... args) {
        ...
       }).doOnDispose(() -> {
            if (!channels.containsKey(channelId)) {
                sendMessage(getUnsubscribeMessage(channelId));
                channels.remove(channelId);
            }
        }).share();
    }
````

**Comment by smakhnist** [comment]
Guys any update on that so far? We are experiencing same issue as well.

**Comment by daniel-cohen** [comment]
@KateKom  I found this issue after looking at the code and noticing what I believe is a wrong condition. So, I believe you're right.
I think it should be:
```
       if (channels.containsKey(channelId)) {
                sendMessage(getUnsubscribeMessage(channelId));
                channels.remove(channelId);
            }
```

**Comment by daniel-cohen** [comment]
What I also don't really understand (and this might be because I am new to RxJava) is this condition:
```
  if (!channels.containsKey(channelId)) {
                Subscription newSubscription = new Subscription(e, channelName, args);
                channels.put(channelId, newSubscription);
                try {
                    sendMessage(getSubscribeMessage(channelName, args));
                } catch (IOException throwable) {
                    e.onError(throwable);
                }
            }
```
Doesn't it mean if someone else already subscribed to the same channel id (channels already contains the key), the subsequent subscription will just sit there idle and never get any events ?
