### ISSUE TITLE
Consider implementing Bitfinex websocket API

### ISSUE THREAD

**Issue by altmind** [bitrich-info/xchange-stream#8]
https://docs.bitfinex.com/v2/docs/ws-general

**Comment by LeonidShamis** [comment]
Hi,
I'd like to try implementing Bitfinex Streaming Exchange.
I have a question:
Taking a simple case of subscribing to Ticker public channel - https://docs.bitfinex.com/v2/reference#ws-public-ticker - I see that it is not sufficient to pass only channel name and action/event (subscribe, unsubscribe). We also need to pass a symbol - specially formatted currency pair (e.g. 'tBTCUSD' for `CurrencyPair.BTC_USD`), for instance:
```
{ 
  event: 'subscribe', 
  channel: 'ticker', 
  symbol: 'tBTCUSD' 
}
```
So, in `BitfinexStreamingMarketDataService` class I would make use of `BitfinexStreamingService` service to subscribe to channel by calling `service.subscribeChannel(channelName)`.
I see that `BitfinexStreamingService` must implement related methods defined in `NettyStreamingService`:
```
protected abstract String getChannelNameFromMessage(T message) throws IOException;
public abstract String getSubscribeMessage(String channelName) throws IOException;
public abstract String getUnsubscribeMessage(String channelName) throws IOException;
```
However, the above methods seems to allow constructing subscribe/unsubscribe message only based on channel name, while Bitfinex also requires a symbol when creating subscribe message.

I compared the above with another similar Streaming Exchange implementation - GDAX - and there I see that it is possible to use the above methods with only channel name (actually it is mapped to currency pair) to create subscribe message like the foloowing:
```
{
    "type": "subscribe",
    "product_id": ""BTC-USD"
}
```
Appreciate your help.

**Comment by dozd** [comment]
Hmm either we should do some refactoring and add varargs into these methods. Then you could be able to pass additional data for the subscribe / unsubscribe messages. Or create another implementation with different interface.

I am not sure what's best approach :).

**Comment by LeonidShamis** [comment]
@dozd  thank you for the prompt response.
I think that your suggestion with refactoring could work.
In https://github.com/LeonidShamis/TestSubscribeChannel repo I have demonstrated simplified current functionality and in https://github.com/LeonidShamis/TestSubscribeChannelWithSymbol I have tried to make the necessary changes to Abstract class method signatures and code to allow the current behavior to still work while also allowing for extra arguments.
If this refactoring approach is fine, I would try applying it to the project and hopefully create PR.

**Comment by LeonidShamis** [comment]
@dozd I have only addressed subscribing to channel, I haven't looked at unsubscribing yet. Please have a look here - https://github.com/bitrich-info/xchange-stream/compare/develop...LeonidShamis:develop
If this is OK, I'll create PR

**Comment by LeonidShamis** [comment]
I've sort of  hit a roadblock due to limited knowledge of RxJava :(
I think that the most important part of implementing WebSocket API for an Exchange is in the implementation of the following 3 methods in `<Exchange>StreamingMarketDataService`:
```
    @Override
    public Observable<OrderBook> getOrderBook(CurrencyPair currencyPair, Object... args) {
    @Override
    public Observable<Ticker> getTicker(CurrencyPair currencyPair, Object... args) {
    @Override
    public Observable<Trade> getTrades(CurrencyPair currencyPair, Object... args) {
```
I know how the data returned by the WebSocket feed looks like, but I haven't figured a way of mapping it (.map(...)) to respective Observable<> streams.

I also noticed that v1 data looks slightly different (and simpler) that v2 data. See attached.

[ticker.v1.txt](https://github.com/bitrich-info/xchange-stream/files/1189484/ticker.v1.txt)
[ticker.v2.txt](https://github.com/bitrich-info/xchange-stream/files/1189485/ticker.v2.txt)
[trades.v1.txt](https://github.com/bitrich-info/xchange-stream/files/1189486/trades.v1.txt)
[trades.v2.txt](https://github.com/bitrich-info/xchange-stream/files/1189487/trades.v2.txt)

**Comment by dozd** [comment]
@LeonidShamis that change to varags seems working for me, create PR.

About mapping - it won't be much different to another exchanges, just look there. You also need to create proper mapping class if they are not similar to polling ones.

**Comment by LeonidShamis** [comment]
Created [PR#12](https://github.com/bitrich-info/xchange-stream/pull/12)

**Comment by dozd** [comment]
Merged. I'd like to see implementation that uses these varargs in subscribing :-).

**Comment by evdubs** [comment]
In case it helps, I had a working Bitfinex WebSocket v2 client using tyrus-standalone-client and dependencies pulled in from xchange-bitfinex. The code is available on [BitBucket](https://bitbucket.org/evdubs/hermaea), and the two important classes are BitfinexWebSocketSecureClient and BitfinexHmacWebsocketAuthDigest. The rest is largely related to saving data, building order books, and executing a strategy. I haven't cleaned it up, and I'm not exactly sure if the libraries are easy to port to from tyrus-standalone-client to whatever xchange-stream uses, so it may be more trouble than its worth. If you happen to have questions about the implementation, let me know.

**Comment by dozd** [comment]
Thanks to @lukaszaoralek
