### ISSUE TITLE
Bitfinex reconnect loop

### ISSUE THREAD

**Issue by scionaltera** [bitrich-info/xchange-stream#82]
I'm seeing the Bitfinex stream get into a reconnect loop in version 4.3.1. On 4.3.2-SNAPSHOT I get issue #81 on the GDAX side instead so it's hard to tell if this is also happening or not.

```
2018-01-23 17:51:29.888 INFO 1 --- [tLoopGroup-65-1] i.b.x.s.netty.WebSocketClientHandler : WebSocket Client disconnected!
2018-01-23 17:51:29.889 INFO 1 --- [tLoopGroup-65-1] i.b.x.s.netty.NettyStreamingService : Reopening websocket because it was closed by the host
2018-01-23 17:51:29.889 INFO 1 --- [tLoopGroup-65-1] i.b.x.s.netty.NettyStreamingService : Connecting to wss://api.bitfinex.com:-1/ws/2
2018-01-23 17:51:30.605 INFO 1 --- [tLoopGroup-66-1] i.b.x.s.netty.WebSocketClientHandler : WebSocket Client connected!
2018-01-23 17:51:30.605 INFO 1 --- [tLoopGroup-65-1] i.b.x.s.netty.NettyStreamingService : Resubscribing channels
2018-01-23 17:51:30.795 ERROR 1 --- [tLoopGroup-66-1] i.b.x.bitfinex.BitfinexStreamingService : Error with message: "channel: unknown"
```

Because it doesn't have the right channel name it can't successfully reconnect but it keeps trying until I kill it. ~So far I've only seen this happen if I leave it running for a long period of time in AWS.~ I just saw it happen locally on my laptop.

I'm running 4.3.2-SNAPSHOT with the change mentioned in #81 now ~to see if this issue got fixed in the develop branch already.~ and it still happens, but seems less frequent.

**Comment by nodarret** [comment]
Problem is with reconnect function which iterates over channelsIds. For bitfinex channelId have overrided method getSubscriptionUniqueId.
Proper message:
`{"event":"subscribe","channel":"book","pair":"LTCUSD","prec":"R0","len":"100"}`
Inproper for reconnect:
`{"event":"subscribe","channel":"book-LTCUSD","pair":"LTCUSD","prec":"R0","len":"100"}`

**Comment by scionaltera** [comment]
Thanks for confirming. That's what I thought I was seeing but I wasn't sure. I'll take a shot at fixing it and see how it goes.

**Comment by nodarret** [comment]
Hi, i think better is change netty-service resubscription instead substring channelName https://github.com/nodarret/xchange-stream/commit/70990f21c7c8bc68b9c4e53a1807dacd49697c51

**Comment by scionaltera** [comment]
That does look better. I was concerned about whether changing it there would break other services. I don't know this code well enough yet to tell.

**Comment by nodarret** [comment]
@scionaltera Your fix works, but when in future Bitfinex want to use "-" in channel name it wont work.
My fix also tested with Bitfinex works, don't know how with other exchanges.
Simplest way with linux to test is use nslookup to know remote IP, change api.bitfinex.com (or other exchange) to 127.0.0.1 in hosts. then use redir on wss port (443) localhost->remote ip and at the end kill redir to force xchange-stream to reconnect.
Unfortunately it reconnects immediately and when redir is not set up it hangs for unknown time (system?), for testing purposes you should use brakepoint before reconnect and then setup redir. I think is another bug. Also is no heartbeat/ping mechanism so when, for example, we block on firewall connection this will take long time (system?) to detect disconnection.

**Comment by scionaltera** [comment]
@nodarret I've had a chance to look at your change more carefully now. I don't see any reason it would interact badly with other exchanges. I encourage you to submit a pull request and see what the project maintainers think.
