### ISSUE TITLE
Consider implementing gemini websocket api

### ISSUE THREAD

**Issue by altmind** [bitrich-info/xchange-stream#9]
https://docs.gemini.com/websocket-api/#create-your-account

**Comment by MartianTech** [comment]
Upvote this. Would really love some help on this.

**Comment by EricAnderson1000** [comment]
I'm interested in working on this. Anyone want to offer a bounty to sweeten the deal? Might get done either way.

**Comment by lukaszaoralek** [comment]
@altmind @MartianTech 
PR #29
