### ISSUE TITLE
The lost dependence

### ISSUE THREAD

**Issue by keekkenen** [bitrich-info/xchange-stream#90]
Please, add reactive-streams artifact in pom file

**Comment by dozd** [comment]
Why?

**Comment by nodarret** [comment]
In #89  i have updated rxjava from 2.0.4 to 2.0.9. They changed scope from runtime to compile. https://github.com/ReactiveX/RxJava/blob/v2.0.9/build.gradle

**Comment by keekkenen** [comment]
mm.. sorry, I am realy wrong.. the IDE too long checked dependencies and I was run example code and I have an Exception..
