### ISSUE TITLE
Synchronization with XChange

### ISSUE THREAD

**Issue by cymp** [bitrich-info/xchange-stream#92]
Hi,

I would like to know if using this library requires a version synchronization with XChange. I mean, should their version be the same. I am using version 4.3.3 of XChange and I can see that XChange-stream version is 4.3.2, should this be a problem?

**Comment by dozd** [comment]
Hello, It depends :). Sometime it could be a problem when there are a lot changes in the API on Xchange side. But i think most of the time it shouldn't.

I try to be up-to-date with released version of the Xchange but if you need to be up-to-date to snapshot version of the Xchange, you can propose PR and we can keep that in separate branch from develop branch.
